---
name: Sync labels
on: # yamllint disable-line rule:truthy
    workflow_dispatch:
    push:
        branches: [main, master]
        paths: [.github/labels.yml]



# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: micnncim/action-label-syncer@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  manifest: .github/labels.yml
